//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrenningEkz
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProd
    {
        public int ID_Prod_Order { get; set; }
        public Nullable<int> ID_Prod { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_PickPoint { get; set; }
    
        public virtual PIckPoint PIckPoint { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
